import os

path = "docs/Guide_Installation_PC_OmenServer_IT.md"
with open(path, "r") as f: content = f.read()

replacements = {
    "Guide Complet — Ajouter un PC au réseau OmenServer": "Guida Completa — Aggiungere un PC alla rete OmenServer",
    "Ce guide explique comment transformer n'importe quel PC": "Questa guida spiega come trasformare qualsiasi PC",
    "en un \"bras\" connecté à OmenServer": "in un \"braccio\" connesso a OmenServer",
    "L'Omen reste le **cerveau** (serveur principal)": "L'Omen rimane il **cervello** (server principale)",
    "les autres PC sont les **bras**": "gli altri PC sono i **bracci**",
    "Table des matières": "Sommario",
    "Prérequis": "Requisiti",
    "Créer la clé USB bootable Ubuntu": "Creare la chiavetta USB avviabile di Ubuntu",
    "Installer Ubuntu Server": "Installare Ubuntu Server",
    "Premier démarrage — Configuration de base": "Primo avvio — Configurazione di base",
    "Activer SSH (accès à distance)": "Attivare SSH (accesso remoto)",
    "Installer l'agent (en 1 seule commande)": "Installare l'agente (in 1 solo comando)",
    "Lancer l'agent au démarrage automatiquement": "Avviare l'agente all'avvio automaticamente",
    "Vérifier que ça fonctionne": "Verificare che funzioni",
    "Commandes optionnelles utiles": "Comandi opzionali utili",
    "Dépannage": "Risoluzione dei problemi",
    "Ce qu'il te faut :": "Cosa ti serve:",
    "Le PC à transformer": "Il PC da trasformare",
    "Une clé USB de 8 Go minimum": "Una chiavetta USB da almeno 8 GB",
    "Un câble Ethernet": "Un cavo Ethernet",
    "Un écran + clavier": "Uno schermo + tastiera",
    "La clé API OmenServer": "La chiave API OmenServer",
    "Ce que le PC va devenir :": "Cosa diventerà il PC:",
    "Un PC sous Linux (Ubuntu Server) sans interface graphique": "Un PC con Linux (Ubuntu Server) senza interfaccia grafica",
    "Il enverra ses stats": "Invierà le sue statistiche",
    "Tu pourras le **redémarrer ou l'éteindre à distance**": "Potrai **riavviarlo o spegnerlo a distanza**",
    "Son **stockage sera fusionné**": "Il suo **storage sarà unito**",
    "Il **restera allumé même capot fermé**": "**Resterà acceso anche col coperchio chiuso**",
    "s'allumera/s'éteindra automatiquement": "si accenderà/spegnerà automaticamente",
    "Extension du disque": "Estensione del disco",
    "étend automatiquement l'espace de base": "espande automaticamente lo spazio di base",
    "Option SSD/HDD": "Opzione SSD/HDD",
    "te demandera si tu veux formater un 2e disque": "ti chiederà se vuoi formattare un 2° disco",
    "Télécharger Ubuntu Server": "Scaricare Ubuntu Server",
    "Sur ton Mac (ou un autre PC), va sur :": "Sul tuo Mac (o un altro PC), vai su:",
    "Télécharge le fichier": "Scarica il file",
    "Créer la clé USB bootable": "Creare la chiavetta USB avviabile",
    "Option A — Sur Mac (avec balenaEtcher)": "Opzione A — Su Mac (con balenaEtcher)",
    "Télécharge **balenaEtcher**": "Scarica **balenaEtcher**",
    "Ouvre balenaEtcher": "Apri balenaEtcher",
    "Clique": "Clicca",
    "sélectionne le fichier": "seleziona il file",
    "sélectionne ta clé USB": "seleziona la tua chiavetta USB",
    "Attends que ça finisse": "Aspetta che finisca",
    "Option B — Sur Windows (avec Rufus)": "Opzione B — Su Windows (con Rufus)",
    "Télécharge **Rufus**": "Scarica **Rufus**",
    "Ouvre Rufus": "Apri Rufus",
    "Périphérique": "Dispositivo",
    "Type de démarrage": "Selezione boot",
    "choisis le fichier": "scegli il file",
    "Laisse les autres options par défaut et clique sur": "Lascia le altre opzioni predefinite e clicca su",
    "Option C — Sur Mac (avec le Terminal)": "Opzione C — Su Mac (con il Terminale)",
    "Trouver le disque de ta clé USB": "Trovare il disco della tua chiavetta USB",
    "Démonter la clé": "Smontare la chiavetta",
    "Écrire l'ISO sur la clé": "Scrivere l'ISO sulla chiavetta",
    "Éjecter la clé": "Espellere la chiavetta",
    "ATTENTION : Vérifie bien le numéro du disque": "ATTENZIONE : Verifica bene il numero del disco",
    "Booter sur la clé USB": "Avviare dalla chiavetta USB",
    "Branche la clé USB sur le PC": "Collega la chiavetta USB al PC",
    "Allume le PC": "Accendi il PC",
    "Appuie sur la **touche de boot**": "Premi il **tasto di boot**",
    "Sélectionne la clé USB dans le menu de boot": "Seleziona la chiavetta USB nel menu di boot",
    "Choisis": "Scegli",
    "Étapes de l'installation": "Fasi dell'installazione",
    "Écran": "Schermata",
    "Quoi faire": "Cosa fare",
    "Langue": "Lingua",
    "Choisis ta langue": "Scegli la tua lingua",
    "Clavier": "Tastiera",
    "Choisis ta disposition clavier": "Scegli il layout della tastiera",
    "Type d'installation": "Tipo di installazione",
    "Réseau": "Rete",
    "Il détecte automatiquement ton câble Ethernet": "Rileva automaticamente il cavo Ethernet",
    "Laisse vide, appuie Entrée": "Lascia vuoto, premi Invio",
    "Laisse par défaut, appuie Entrée": "Lascia predefinito, premi Invio",
    "Stockage": "Archiviazione",
    "IMPORTANT": "IMPORTANTE",
    "Nom / Utilisateur": "Nome / Utente",
    "Voir ci-dessous": "Vedi sotto",
    "Coche": "Spunta",
    "Ne coche rien, appuie Entrée": "Non spuntare nulla, premi Invio",
    "Configuration du stockage": "Configurazione dell'archiviazione",
    "L'installateur propose un schéma de partition. **Par défaut, Ubuntu n'utilise pas tout l'espace !**": "L'installer propone uno schema di partizioni. **Di default, Ubuntu non usa tutto lo spazio!**",
    "Option recommandée :": "Opzione consigliata:",
    "Si le PC a plusieurs disques, choisis le **plus gros** pour le système": "Se il PC ha più dischi, scegli il **più grande** per il sistema",
    "Vérifie que le `lvm` est activé": "Verifica che `lvm` sia attivato",
    "Pas de panique : même si Ubuntu ne prend pas tout l'espace au départ, on l'étendra après": "Niente panico: anche se Ubuntu non usa tutto lo spazio all'inizio, lo espanderemo dopo",
    "Nom et utilisateur": "Nome e utente",
    "Champ": "Campo",
    "Quoi mettre": "Cosa inserire",
    "Exemple": "Esempio",
    "Ton prénom": "Il tuo nome",
    "Un nom court pour le PC": "Un nome breve per il PC",
    "Ton identifiant": "Il tuo ID utente",
    "le même que l'Omen, c'est plus simple": "lo stesso dell'Omen, è più semplice",
    "Un mot de passe solide": "Una password sicura",
    "Fin de l'installation": "Fine dell'installazione",
    "L'installation prend": "L'installazione richiede",
    "Quand c'est fini, il te demande de": "Quando è finito, ti chiede di",
    "retirer la clé USB": "rimuovere la chiavetta USB",
    "et appuyer Entrée": "e premere Invio",
    "Le PC redémarre sous Ubuntu Server": "Il PC si riavvia in Ubuntu Server",
    "Tu vois un écran noir avec": "Vedi uno schermo nero con",
    "c'est normal, c'est ça Ubuntu Server": "è normale, questo è Ubuntu Server",
    "Se connecter": "Accedere",
    "ton mot de passe": "la tua password",
    "Mettre à jour le système": "Aggiornare il sistema",
    "Ça peut prendre 5-10 minutes la première fois": "Può richiedere 5-10 minuti la prima volta",
    "Installer les outils essentiels": "Installare gli strumenti essenziali",
    "Explication de chaque paquet": "Spiegazione di ogni pacchetto",
    "Le langage de programmation pour l'agent": "Il linguaggio di programmazione per l'agente",
    "L'installateur de paquets Python": "L'installer dei pacchetti Python",
    "Pour créer des environnements Python isolés": "Per creare ambienti Python isolati",
    "Pour télécharger des fichiers": "Per scaricare file",
    "Pour voir l'utilisation CPU/RAM en temps réel": "Per vedere l'uso CPU/RAM in tempo reale",
    "Pour les commandes réseau": "Per i comandi di rete",
    "Trouver l'IP du PC (pour SSH)": "Trovare l'IP del PC (per SSH)",
    "Note l'adresse IP": "Prendi nota dell'indirizzo IP",
    "Tu en auras besoin pour te connecter à distance": "Ti servirà per connetterti a distanza",
    "Vérifier que SSH est installé": "Verificare che SSH sia installato",
    "Si c'est": "Se è",
    "c'est bon ! Sinon :": "va bene! Altrimenti:",
    "Se connecter depuis le Mac": "Connettersi dal Mac",
    "Ouvre un Terminal sur ton Mac et tape :": "Apri un Terminale sul tuo Mac e digita:",
    "Remplace `XX` par le dernier chiffre de l'IP du PC": "Sostituisci `XX` con le ultime cifre dell'IP del PC",
    "Tu es maintenant connecté à distance ! **Tu peux débrancher l'écran et le clavier du PC.**": "Ora sei connesso a distanza! **Puoi scollegare schermo e tastiera dal PC.**",
    "Pour simplifier au maximum, un script s'occupe de **tout** installer et configurer automatiquement :": "Per semplificare al massimo, uno script si occupa di installare e configurare **tutto** automaticamente:",
    "Téléchargement de l'agent": "Download dell'agente",
    "Configuration de la clé API": "Configurazione della chiave API",
    "Lancement automatique au démarrage": "Avvio automatico",
    "service en arrière-plan": "servizio in background",
    "Fermeture du capot": "Chiusura del coperchio",
    "le PC restera allumé même si tu fermes l'écran": "il PC resterà acceso anche se chiudi lo schermo",
    "Horaires automatiques": "Orari automatici",
    "le PC s'éteindra à 1h du matin et se rallumera à 6h du matin": "il PC si spegnerà all'1 di notte e si riaccenderà alle 6 del mattino",
    "Lancer l'installation": "Avviare l'installazione",
    "connecte-toi, et va dans les": "accedi, e vai nelle",
    "Paramètres": "Impostazioni",
    "pour copier ta": "per copiare la tua",
    "Clé API": "Chiave API",
    "Sur le nouveau PC, tape cette commande en remplaçant `TA_CLE_API` par ta vraie clé (par exemple": "Sul nuovo PC, digita questo comando sostituendo `TA_CLE_API` con la tua vera chiave (per esempio",
    "(Si ça te demande un mot de passe, c'est celui de ta session ubuntu)": "(Se ti chiede una password, è quella della tua sessione ubuntu)",
    "Attends 1 minute. À la fin, le script te demandera :": "Attendi 1 minuto. Alla fine, lo script ti chiederà:",
    "As-tu un deuxième disque (SSD/HDD) que tu veux effacer": "Hai un secondo disco (SSD/HDD) che vuoi cancellare",
    "Tape `y` si tu as un vieux disque à formater (ATTENTION : efface TOUT), ou juste `Entrée` pour ignorer.": "Digita `y` se hai un vecchio disco da formattare (ATTENZIONE: cancella TUTTO), o solo `Invio` per ignorare.",
    "Quand tu vois `✅ Terminé !`, c'est fini.": "Quando vedi `✅ Terminé !`, hai finito.",
    "C'est tout !": "È tutto!",
    "Tu peux maintenant :": "Ora puoi:",
    "Fermer le capot de l'ordinateur": "Chiudere il coperchio del computer",
    "il restera allumé": "resterà acceso",
    "Le ranger dans une étagère avec son câble d'alimentation": "Riporlo su uno scaffale col suo cavo di alimentazione",
    "Le gérer entièrement depuis le dashboard OmenServer": "Gestirlo interamente dalla dashboard di OmenServer",
    "Étendre le disque (si Ubuntu n'utilise pas tout l'espace)": "Estendere il disco (se Ubuntu non usa tutto lo spazio)",
    "C'est le problème le plus courant : Ubuntu Server avec LVM n'utilise que ~100 Go par défaut.": "È il problema più comune: Ubuntu Server con LVM usa solo ~100 GB di default.",
    "Voir l'espace actuel": "Vedere lo spazio attuale",
    "Voir les disques physiques": "Vedere i dischi fisici",
    "Étendre le volume logique pour utiliser tout l'espace libre": "Estendere il volume logico per usare tutto lo spazio libero",
    "Redimensionner le système de fichiers": "Ridimensionare il file system",
    "Vérifier que c'est bon": "Verificare che sia a posto",
    "Formater et utiliser un SSD/HDD supplémentaire": "Formattare e usare un SSD/HDD aggiuntivo",
    "Si le PC a un deuxième disque (SSD ou HDD) pas utilisé :": "Se il PC ha un secondo disco (SSD o HDD) non utilizzato:",
    "Identifier le disque": "Identificare il disco",
    "Voir ce qu'il contient": "Vedere cosa contiene",
    "Effacer toutes les partitions": "Cancellare tutte le partizioni",
    "Créer une partition unique": "Creare una partizione unica",
    "Formater en ext4": "Formattare in ext4",
    "Créer le point de montage et monter": "Creare il punto di mount e montare",
    "Ajouter au démarrage automatique": "Aggiungere all'avvio automatico",
    "Vérifier": "Verificare",
    "Remplace `/dev/sdX` par le vrai nom du disque": "Sostituisci `/dev/sdX` col vero nome del disco",
    "Vider complètement un SSD (effacer toutes les données)": "Svuotare completamente un SSD (cancellare tutti i dati)",
    "ATTENTION : Ceci efface TOUT sur le disque !": "ATTENZIONE : Questo cancella TUTTO sul disco!",
    "Démonter le disque s'il est monté": "Smontare il disco se è montato",
    "Effacer les partitions": "Cancellare le partizioni",
    "Écrire des zéros (effacement complet — peut prendre longtemps)": "Scrivere zeri (cancellazione completa — può richiedere molto tempo)",
    "Re-partitionner si tu veux le réutiliser (voir section précédente)": "Ripartizionare se vuoi riutilizzarlo (vedi sezione precedente)",
    "Configurer une IP fixe (recommandé pour un serveur)": "Configurare un IP statico (consigliato per un server)",
    "Par défaut, l'IP peut changer à chaque redémarrage. Pour la fixer :": "Di default, l'IP può cambiare a ogni riavvio. Per fissarlo:",
    "Trouver le nom de ton interface réseau": "Trovare il nome della tua interfaccia di rete",
    "Note le nom": "Prendi nota del nome",
    "Créer la configuration Netplan": "Creare la configurazione Netplan",
    "Contenu du fichier (adapte selon ton réseau) :": "Contenuto del file (adatta alla tua rete):",
    "Nom de ton interface": "Nome della tua interfaccia",
    "IP fixe que tu veux": "IP statico che desideri",
    "IP de ta box internet": "IP del tuo router internet",
    "Appliquer": "Applicare",
    "Configurer SSH sans mot de passe (clé SSH)": "Configurare SSH senza password (chiave SSH)",
    "Pour ne plus taper le mot de passe à chaque connexion SSH :": "Per non dover più digitare la password a ogni connessione SSH:",
    "Générer une clé SSH (si pas déjà fait)": "Generare una chiave SSH (se non già fatto)",
    "Copier la clé sur le PC distant": "Copiare la chiave sul PC remoto",
    "Maintenant tu peux te connecter sans mot de passe :": "Ora puoi connetterti senza password:",
    "Voir l'utilisation du système en temps réel": "Vedere l'uso del sistema in tempo reale",
    "CPU, RAM en temps réel (comme un gestionnaire de tâches)": "CPU, RAM in tempo reale (come un task manager)",
    "Utilisation disque": "Uso del disco",
    "Température CPU": "Temperatura CPU",
    "Divise par 1000 pour avoir les °C": "Dividi per 1000 per avere i °C",
    "Processus les plus gourmands": "Processi più esigenti",
    "Connexions réseau actives": "Connessioni di rete attive",
    "Mises à jour classiques": "Aggiornamenti classici",
    "Mises à jour de sécurité automatiques": "Aggiornamenti di sicurezza automatici",
    "Éteindre maintenant": "Spegnere ora",
    "Redémarrer maintenant": "Riavviare ora",
    "Éteindre dans 30 minutes": "Spegnere tra 30 minuti",
    "Annuler un shutdown programmé": "Annullare uno spegnimento programmato",
    "Tester la connexion à OmenServer": "Testare la connessione a OmenServer",
    "Tester la connexion internet": "Testare la connessione internet",
    "Voir l'IP actuelle": "Vedere l'IP attuale",
    "Scanner les PC du réseau local": "Scansionare i PC nella rete locale",
    "L'agent ne se connecte pas au serveur": "L'agente non si connette al server",
    "Vérifier que le service tourne": "Verificare che il servizio sia in esecuzione",
    "Voir les erreurs dans les logs": "Vedere gli errori nei log",
    "Tester la connexion manuellement": "Testare la connessione manualmente",
    "Vérifier la clé API dans le fichier": "Verificare la chiave API nel file",
    "Causes fréquentes :": "Cause frequenti :",
    "Mauvaise clé API → vérifie dans le dashboard": "Chiave API errata → controlla nella dashboard",
    "Pas de connexion internet → vérifie le câble Ethernet": "Nessuna connessione internet → controlla il cavo Ethernet",
    "Firewall bloque": "Il firewall blocca",
    "Le PC n'apparaît pas dans le dashboard": "Il PC non appare nella dashboard",
    "Attends **30 secondes** après le démarrage de l'agent": "Attendi **30 secondi** dopo l'avvio dell'agente",
    "Vérifie que l'agent est en": "Verifica che l'agente sia in",
    "Vérifie les logs": "Controlla i log",
    "Le disque affiche moins d'espace que prévu": "Il disco mostra meno spazio del previsto",
    "Utilise la commande d'extension LVM": "Usa il comando di estensione LVM",
    "Le PC est \"offline\" dans le dashboard mais il tourne": "Il PC è \"offline\" nella dashboard ma è acceso",
    "L'agent s'est peut-être crashé": "L'agente potrebbe essersi bloccato",
    "Le réseau est peut-être coupé": "La rete potrebbe essere interrotta",
    "SSH refusé": "SSH rifiutato",
    "Sur le PC (avec écran+clavier), vérifie que SSH tourne": "Sul PC (con schermo+tastiera), verifica che SSH sia in esecuzione",
    "Si non installé": "Se non installato",
    "Vérifier le firewall": "Verificare il firewall",
    "Checklist rapide (résumé)": "Checklist rapida (riassunto)",
    "Pour chaque nouveau PC, fais ces étapes dans l'ordre :": "Per ogni nuovo PC, fai questi passaggi in ordine:",
    "Installer Ubuntu Server (cocher SSH !)": "Installare Ubuntu Server (spuntare SSH!)",
    "Se connecter et mettre à jour": "Connettersi e aggiornare",
    "Installer python": "Installare python",
    "Lancer le script d'installation auto": "Lanciare lo script di installazione auto",
    "Vérifier sur le dashboard OmenServer": "Verificare sulla dashboard OmenServer",
    "Étendre le disque LVM": "Estendere il disco LVM",
    "Formater un SSD supplémentaire": "Formattare un SSD aggiuntivo",
    "Configurer une IP fixe": "Configurare un IP statico",
    "Configurer SSH sans mot de passe": "Configurare SSH senza password",
    "Tous connectés, tout fusionné, tout contrôlé depuis un seul dashboard.": "Tutti connessi, tutto unito, tutto controllato da un'unica dashboard."
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(path, "w") as f: f.write(content)
